name: Build & Push Gateway API

on:
  push:
    branches: [ main ]
    paths:
      - "gateway/**"
      - ".github/workflows/build-gateway-api.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
      ECR_REPO: my-gateway-api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin \
              $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build & Push Docker image
        run: |
          IMAGE_URI=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$(date +%Y%m%d%H%M)
          docker build -t $IMAGE_URI ./gateway
          docker push $IMAGE_URI
